[theme]
primaryColor = "#00ffff"
backgroundColor = "#050509"
secondaryBackgroundColor = "#0d0d1a"
textColor = "#f5f5f5"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = true

